name: Escalate GitHub Issues

on:
  schedule:
    - cron: "*/5 * * * *"
  issues:
    types:
      - labeled
      - opened
      - edited
      - syncronized

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue Label and Status
      id: check_label_status
      run: |
        # Use the GitHub API to fetch issue labels and status (you'll need a GitHub token with appropriate permissions)
        issue_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }})

        echo "$issue_data"

        # Extract label and status
        labels=$(echo "$issue_data" | jq -r '.labels[].name')
        status=$(echo "$issue_data" | jq -r '.state')

        # Check if the "pagerDuty" label is present and the status is not closed
        if [[ "$labels" =~ "pager-duty" ]] && [[ "$status" != "closed" ]]; then
          echo "LABEL_PRESENT=true" >> $GITHUB_ENV
        else
          echo "LABEL_PRESENT=false" >> $GITHUB_ENV
        fi

    - name: Check if Issue Was Opened More Than 2 Days Ago
      if: env.LABEL_PRESENT == 'true'
      run: |
        # Use GitHub API to get the issue's created timestamp
        created_at=$(echo "$issue_data" | jq -r '.created_at')

        # Calculate the current date and 2 minutes ago
        current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        two_days_ago=$(date -u -d '2 days ago' +%Y-%m-%dT%H:%M:%SZ)


        # Check if the issue was created more than 2 days ago
        if [[ "$created_at" < "two_days_ago" ]]; then
          # Use GitHub API to assign the issue to Shubham
          username="Shubham9t9"

          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"assignees\": [\"$username\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees"
        else
          echo "Issue is not older than 2 minutes or it's already closed. No escalation needed."
        fi
